global using GameZone.Data;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using GameZone.Settings;
global using GameZone.Resources;
global using GameZone.Models;
global using Microsoft.Extensions.Localization;
global using GameZone.Models;
